### PR TITLE
adding availability to item ui and fixing some things on the side

### LINKED ISSUE #312: Item UI: Availability
[https://github.com/EPFLSWENT2024G1/partagix/pull/292](https://github.com/EPFLSWENT2024G1/partagix/pull/292) added a way to avoid overlapping loans.

Your task:
- The `ItemUI` should display the information if the item is available from now (in green, positive text), or the date when it becomes available.
- Quickly modify the test to include this information (you can ignore this if you have enough coverage)

### PR DESCRIPTION
**Pull request by skyrag**
implement the fact tat we now know the date at which we should have our item back or when it is available or not, also fixing the fact that we could make a loan for an item with a start date after the endate, erase some to do comments

### CODE REVIEW

File: app/src/main/java/com/android/partagix/model/BorrowViewModel.kt [hunk 1]
```diff
@@ -122,7 +127,9 @@ class BorrowViewModel(
               Notification(
                   title = "New incoming request",
                   message =
-                      "You have a new incoming request for your item: ${item.name}, from ${dateFormat( loan.startDate)} to ${dateFormat( loan.endDate)}",
+                      "You have a new incoming request for your item: ${item.name}," +
+                          " from ${displayedDateFormat( loan.startDate)}" +
```
Comment (Patrick-Pataky) [inline app/src/main/java/com/android/partagix/model/BorrowViewModel.kt:131]: Much better date display now

File: app/src/main/java/com/android/partagix/model/InventoryViewModel.kt [hunk 2]
```diff
@@ -95,10 +98,17 @@ class InventoryViewModel(
...
             loansList
                 .filter { it.idBorrower.equals(currentUser.uid) }
                 .filter { it.state == LoanState.ACCEPTED || it.state == LoanState.ONGOING }
                 .forEach { loan ->
+                  availabilityBor.add(
+                      if (loan.startDate.before(Date()) && loan.endDate.after(Date())) {
+                        true
+                      } else {
+                        false
+                      })
```
Comment (Patrick-Pataky) [inline app/src/main/java/com/android/partagix/model/InventoryViewModel.kt:111]: For better readability: 

```suggestion
                  availability.add(loan.startDate.before(Date()) && loan.endDate.after(Date()))
```

File: app/src/main/java/com/android/partagix/model/InventoryViewModel.kt [hunk 3]
```diff
@@ -119,6 +129,21 @@ class InventoryViewModel(
...
+                .filter { it.idUser.equals(currentUser.uid) }
+                .forEach { item ->
+                  println(item)
+                  database.getItemUnavailability(item.id) { date ->
+                    availability.add(
+                        if (date.none { stripTime(it) == stripTime(Date()) }) {
+                          true
+                        } else {
+                          false
+                        })
```
Comment (Patrick-Pataky) [inline app/src/main/java/com/android/partagix/model/InventoryViewModel.kt:143]: For better readability:

```suggestion
                    availability.add(date.none { stripTime(it) == stripTime(Date()) }))
```

File: app/src/main/java/com/android/partagix/model/LoanViewModel.kt [hunk 4]
```diff
@@ -45,14 +47,27 @@ class LoanViewModel(
...
                 }
             applyFilters(uiState.value.filterState)
+            newItems.map { item ->
+              db.getItemUnavailability(item.id) { date ->
+                newAvailabilityList.add(
+                    if (date.none { stripTime(it) == stripTime(Date()) }) {
+                      true
+                    } else {
+                      false
+                    })
```
Comment (Patrick-Pataky) [inline app/src/main/java/com/android/partagix/model/LoanViewModel.kt:65]: For better readability:

```suggestion
                newAvailabilityList.add(date.none { stripTime(it) == stripTime(Date()) })
```

File: app/src/main/java/com/android/partagix/ui/components/ItemList.kt [hunk 5]
```diff
@@ -99,11 +100,21 @@ fun ItemList(
...
+          available =
+              if (availability.isEmpty()) {
+                true
+              } else {
+                if (availability.size <= index) {
+                  true
+                } else {
+                  availability[index]
+                }
+              },
```
Comment (Patrick-Pataky) [inline app/src/main/java/com/android/partagix/ui/components/ItemList.kt:112]: For better readability & less cognitive complexity:

```suggestion
          available = availability.getOrElse(index) { true },
```

File: app/src/main/java/com/android/partagix/ui/components/ItemUi.kt [hunk 6]
```diff
@@ -103,27 +103,19 @@ fun ItemUi(
...
-      }
   var expanded by remember { mutableStateOf(expandState) }
-  val formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy")
-
-  val available = true // TODO
   var availability = "Now available"
-
   if (!available) {
-    availability = "Unavailable"
+    availability = "unavailable now"
```
Comment (Patrick-Pataky) [inline app/src/main/java/com/android/partagix/ui/components/ItemUi.kt:109]:
```suggestion
    availability = "Unavailable now"
```

File: app/src/main/java/com/android/partagix/ui/components/ItemUi.kt [hunk 7]
```diff
@@ -103,27 +103,19 @@ fun ItemUi(
...
+  if (isBorrower && loan.state == LoanState.ACCEPTED) {
     availability = "Accepted but not started"
   }
-  if (isLender && (loan.state == LoanState.ONGOING)) { // normal case of borrowed item
-    availability = ""
+  if (isBorrower && loan.state == LoanState.ONGOING) { // normal case of borrowed item
+    availability = "Available"
+  }
+  if (isOwner && !available) { // normal case of borrowed item
+    availability = "borrowed"
```
Comment (Patrick-Pataky) [inline app/src/main/java/com/android/partagix/ui/components/ItemUi.kt:118]: This text is displayed to the user. It should be properly formatted
```suggestion
    availability = "Borrowed"
```

File: app/src/main/java/com/android/partagix/ui/screens/InventoryViewItemScreen.kt [hunk 8]
```diff
@@ -189,7 +190,17 @@ fun InventoryViewItemScreen(
                         verticalAlignment = Alignment.CenterVertically,
                         horizontalArrangement = Arrangement.SpaceBetween) {
                           Text(
-                              text = "available", /*TODO: get item disponibility*/
+                              text =
+                                  if (uiState.value.unavailableDates.none {
+                                    stripTime(it) == stripTime(Date())
+                                  } && uiState.value.unavailableDates.isNotEmpty()) {
+                                    "unavailable until " +
```
Comment (Patrick-Pataky) [inline app/src/main/java/com/android/partagix/ui/screens/InventoryViewItemScreen.kt:197]:
```suggestion
                                    "Unavailable until " +
```

File: app/src/main/java/com/android/partagix/ui/screens/InventoryViewItemScreen.kt [hunk 9]
```diff
@@ -189,7 +190,17 @@ fun InventoryViewItemScreen(
...
+                                        displayedDateFormat(
+                                            uiState.value.unavailableDates
+                                                .sorted()[uiState.value.unavailableDates.size - 1])
+                                  } else {
+                                    "available"
```
Comment (Patrick-Pataky) [inline app/src/main/java/com/android/partagix/ui/screens/InventoryViewItemScreen.kt:202]:
```suggestion
                                    "Available"
```

**Review by Patrick-Pataky — CHANGES_REQUESTED** [review]
Globally very good modifications, good job !

Aside from the small modifications,
- `ItemList`: can you remove the commented code around line 80 ?

**Review by Patrick-Pataky — APPROVED** [review]
Perfect
